services:
  eureka-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - "8761:8761"
    container_name: eureka-service
    restart: unless-stopped
    networks:
      - healthcare-service-network

networks:
  healthcare-service-network:
    external: true