services:
  user-service-db:
    image: postgres:14
    container_name: user-service-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - healthcare-service-network
    volumes:
      - user_service_db_data:/var/lib/postgresql/data

  notification-service-db:
    image: postgres:14
    container_name: notification-service-db
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: notification-service
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - healthcare-service-network
    volumes:
      - notification_service_db_data:/var/lib/postgresql/data

  metamodel-service-db:
    image: postgres:14
    container_name: metamodel-service-db
    environment:
      POSTGRES_DB: metamodeldb
      POSTGRES_USER: metamodel-service
      POSTGRES_PASSWORD: ${METAMODELE_DB_PASSWORD}
    ports:
      - "5434:5432"
    networks:
      - healthcare-service-network
    volumes:
      - metamodel_service_db_data:/var/lib/postgresql/data

networks:
  healthcare-service-network:
    external: true

volumes:
  user_service_db_data:
      driver: local
  notification_service_db_data:
      driver: local
  metamodel_service_db_data:
      driver: local
