services:
  api-gateway:
    image: apigateway:latest
    ports:
      - "8080:8080"
    networks:
      - healthcare-net

  user-service:
    image: userservice:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: user_service
      SPRING_DATASOURCE_PASSWORD: ${USER_DB_PASSWORD}
    depends_on:
      - user-service-db
      - kafka
    networks:
      - healthcare-net

  user-service-db:
    image: postgres:14
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    networks:
      - healthcare-net

  metamodel-service:
    image: metamodelservice:latest
    environment:
      METAMODELE_DB_PASSWORD: ${METAMODELE_DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://metamodel-service-db:5432/metamodeldb
    depends_on:
      - metamodel-service-db
      - kafka
    networks:
      - healthcare-net

  metamodel-service-db:
    image: postgres:14
    environment:
      POSTGRES_DB: metamodeldb
      POSTGRES_USER: metamodel_service
      POSTGRES_PASSWORD: ${METAMODELE_DB_PASSWORD}
    networks:
      - healthcare-net

  medical-record-service:
    image: medicalrecordservice:latest
    environment:
      MEDICAL_RECORD_DB_PASSWORD: ${MEDICAL_RECORD_DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://medical-record-service-db:5432/medicalrecorddb
    depends_on:
      - medical-record-service-db
      - kafka
    networks:
      - healthcare-net

  medical-record-service-db:
    image: postgres:14
    environment:
      POSTGRES_DB: medicalrecorddb
      POSTGRES_USER: medical_record_service
      POSTGRES_PASSWORD: ${MEDICAL_RECORD_DB_PASSWORD}
    networks:
      - healthcare-net

  medical-component-service:
    image: medicalcomponentservice:latest
    environment:
      MEDICAL_COMPONENT_DB_PASSWORD: ${MEDICAL_COMPONENT_DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://medical-component-service-db:5432/medicalcomponentdb
    depends_on:
      - medical-component-service-db
      - kafka
    networks:
      - healthcare-net

  medical-component-service-db:
    image: postgres:14
    environment:
      POSTGRES_DB: medicalcomponentdb
      POSTGRES_USER: medical_component_service
      POSTGRES_PASSWORD: ${MEDICAL_COMPONENT_DB_PASSWORD}
    networks:
      - healthcare-net

  notification-service:
    image: notificationservice:latest
    environment:
      NOTIFICATION_DB_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-service-db:5432/notificationdb
    depends_on:
      - notification-service-db
      - kafka
    networks:
      - healthcare-net

  notification-service-db:
    image: postgres:14
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: notification_service
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
    networks:
      - healthcare-net

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    networks:
      - healthcare-net

networks:
  healthcare-net:
    driver: overlay
