services:
  user-service-db:
    image: postgres:14
    container_name: user-service-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "5432:5432"

  notification-service-db:
    image: postgres:14
    container_name: notification-service-db
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: notification-service
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
    ports:
      - "5433:5432"

  metamodel-service-db:
    image: postgres:14
    container_name: metamodel-service-db
    environment:
      POSTGRES_DB: metamodeldb
      POSTGRES_USER: metamodel-service
      POSTGRES_PASSWORD: ${METAMODELE_DB_PASSWORD}
    ports:
      - "5434:5432"