services:
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: config-server:latest
    ports:
      - "8888:8888"
    container_name: config-server
    restart: unless-stopped
    networks:
      - healthcare-service-network

networks:
  healthcare-service-network:
    external: true