services:
  user-service-db:
    image: postgres:latest
    container_name: user-service-db
    networks:
      - healthcare-net
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U user_service -d userdb'"]
      interval: 10s
      retries: 5
      start_period: 5s

  user-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: user-test
    networks:
      - healthcare-net
    environment:
      PGPASSWORD: ${USER_DB_PASSWORD}
    depends_on:
      user-service-db:
        condition: service_healthy

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - healthcare-net
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: user_service
      SPRING_DATASOURCE_PASSWORD: ${USER_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
    command: mvn spring-boot:run -Dspring.profiles.active=dev
    depends_on:
      - user-test
      - user-service-db

networks:
  healthcare-net:
    driver: bridge
